### PR TITLE
Fix: check that the infra section exists before infra phase

### LINKED ISSUE #200: Handle no infrastructure with --phase infrastructure in create/delete cmd
Furyctl should throw an error if create/delete cluster cmd is executed with --phase infrastructure but there is no infrastructure in the furyct.yaml file.

### PR DESCRIPTION
**Pull request by Al-Pragliola**
fixes #200

### CODE REVIEW

File: internal/apis/kfd/v1alpha2/eks/creator.go [hunk 1]
```diff
@@ -24,7 +24,10 @@ import (
 	kubex "github.com/sighupio/furyctl/internal/x/kube"
 )
 
-var ErrUnsupportedPhase = errors.New("unsupported phase")
+var (
+	ErrUnsupportedPhase = errors.New("unsupported phase")
+	ErrInfraNotPresent  = errors.New("cluster configuration does not contain infrastructure section")
```
Comment (ralgozino) [inline internal/apis/kfd/v1alpha2/eks/creator.go:29]:
```suggestion
	ErrInfraNotPresent  = errors.New("configuration file does not contain infrastructure section")
```

if we could add also the path to the file, that would be even better

**Review by ralgozino — CHANGES_REQUESTED** [review]

File: internal/apis/kfd/v1alpha2/eks/creator.go (hunk 1 above)
Comment (Al-Pragliola) [reply internal/apis/kfd/v1alpha2/eks/creator.go]: now is something like:
```
ERRO error while creating cluster: the configuration file does not contain an infrastructure section: check at /path/to/furyctl.yaml
```

**Review by ralgozino — APPROVED** [review]
lgtm
